### ISSUE TITLE
Add option to disable based on url pattern

### ISSUE THREAD

**Issue by hjri** [DmitriK/darkContrast#14]
Currenly the addon confilcts with DarkGithub ( https://github.com/StylishThemes/GitHub-Dark ) userstyle, making some elements (not necessarily inputs) dark-on-light, forcing me to manually deactivate extension via toggle every time I visit github page. For those broken cases it would be nice to have a blacklist where addon is initially disabled.

**Comment by DmitriK** [comment]
Added functionality for override lists in 9bf3c588820c0c4d22006e3d9c30930cdb242c64, which is in the 1.3.0 release. Should be available on AMO now, give it a shot.

**Comment by hjri** [comment]
Works pretty good, thanks!

p.s. sorry for late response.
