### ISSUE TITLE
Titles look wonky on reddit.com

### ISSUE THREAD

**Issue by juhrom** [DmitriK/darkContrast#17]
On reddit.com, I noted that thedark theme makes titles black, but this app changes the black color a dark gray.  Thsi makes the titles unreadable.  I'm using the Dark Theme:
 https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj

if I'm in error and using the wrong / improper theme, please let me know.

**Comment by DmitriK** [comment]
Could you attach a screenshot of exactly what you are seeing? Can you also specify what options you have turned on for dark mode (which mode, and whether the reddit override is active). I tried installing the Dark Mode Firefox extension and went to reddit, and while there are some parts with poor contrast, the titles look fine. It's possible that the order the extensions are applied has an effect, which may be based on install order, but without seeing it I can't be certain.

**Comment by juhrom** [comment]
sorry about this.  I'm not using that browser anymore.
