### ISSUE TITLE
uMatrix addon

### ISSUE THREAD

**Issue by whoizit** [DmitriK/darkContrast#21]
not working on chrome://umatrix/content/dashboard.html#user-rules if I press Change button, but needed

**Comment by DmitriK** [comment]
I've struggled with the uMatrix interface myself. Unfortunately it is impossible for the my extension to run under "chrome://" URLs (see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns, not that only http[s], ftp, file, and app are supported. Extension uses <all_urls> which covers everything possible). The only thing to do is to have the uMatrix author fix it on their end.
