### ISSUE TITLE
Still A Little Work

### ISSUE THREAD

**Issue by caltrop2075** [DmitriK/darkContrast#24]
Pretty good but...

Upper left History Bar, Light on Light

https://scontent-ort2-1.xx.fbcdn.net/v/t1.0-9/20842205_803928763065532_2265086884467751472_n.jpg?oh=b8fb414cd54eb31d048b91b4770512d3&oe=5A21007D

**Comment by DmitriK** [comment]
The sidebar header is part of the browser's own theme. This extension can't fix that.

You'll probably need to fix it via userChrome.css. The `.sidebar-header, #sidebar-header` selector can be used to modify that element. For what it's worth, I'm using the compact dark theme and the header works for me (other than being way too big by default for my tastes).
