### ISSUE TITLE
Please offer whitelist instead of blacklist

### ISSUE THREAD

**Issue by wolftune** [DmitriK/darkContrast#30]
With my plugins and themes, everything almost always works. This plugin usually then breaks things. But sometimes, it's wrong and this plugin fixes it. I really want a mode where this is off by default and turns on only for whitelisted pages/sites.

**Comment by DmitriK** [comment]
The request sounds reasonable. I'm in the middle of doing a re-write of the basic functionality, so it may take a bit for me to get to.
In the meantime, you can try using the delay feature. It was specifically added to try and avoid conflict with other extensions. Go to the override list page, and you'll see a 'Delay (Beta)' entry where you can add a time. This controls how long the extension waits before analyzing the page and adding fixes. You can try starting with an extreme value, like 1000ms, and if it works, reduce it until the delay is acceptable.

**Comment by wolftune** [comment]
Thanks, and the delay before analyzing will itself mean it will see the effects of the other plugins and only fix if it still is evaluated as needed?

**Comment by DmitriK** [comment]
Yes, that's the idea. I use a delay of 32ms myself to let my custom CSS extension a chance to inject what it needs to, then this extension fixes what's left.

**Comment by wolftune** [comment]
That's not solving it. I see the delay, but with "Dark Background and Light Text" plugin on, everything looks fine here on GitHub, and then your plugin kicks in eventually and turns it to black on black. (The dialog while typing this is fine, and the headers over each comment are fine, but the content of each comment is black on black)

**Comment by DmitriK** [comment]
Whitelist has been added in the latest 2.0.x series. Please check to see if it works for your needs.

**Comment by wolftune** [comment]
Great! I'll try it!

I must say that it seems odd to have one list that can flip from whitelist to blacklist. Although it makes no sense to use both a whitelist and blacklist, it certainly makes no sense to switch the same list between those two states. If someone wants to try each approach, it makes more sense to keep the lists as two separate lists.

**Comment by xnick** [comment]
The whitelist works great for me. But I keep having to copy the url, open the options menu and paste it in the list. Could you add a button in the icon menu to add the current page or domain to the whitelist?

**Comment by mlissner** [comment]
I actually have a use case for a whitelist and a blacklist. 

 - Whitelist: Mostly I don't want the extension to do anything, so I just want to enable it for some certain sites as they have problems.
 - Blacklist: I don't want this extension to do anything on the pages that I do web-dev for, or that I'm the administrator for. For those, I need to see them in their normal state, so I can fix this issue at the root.

Maybe have one list, and allow items to be pre-pended with a `+` or `-` sign?

**Comment by DmitriK** [comment]
There's a few separate other issues that have been brought up, so I'm going to open some new issues for them, and close this one as it solves the original request for a whitelist.

@mlissner The two kinds of lists really should be mutually exclusive. If you are in whitelist mode, only sites on the whitelist are touched, so sites you do web-dev for won't be affected so long as they don't end up in the list. Alternatively, in blacklist mode add your web-dev urls to the list and let the extension try to fix everything else.
