### ISSUE TITLE
The starting page of FF57 doesn’t work

### ISSUE THREAD

**Issue by fbruetting** [DmitriK/darkContrast#32]
I here use the Adapta theme on Fedora 27.

![bildschirmfoto von 2017-11-27 01-41-16](https://user-images.githubusercontent.com/10520767/33246383-1c7654fc-d314-11e7-96c8-6671f57b1b58.png)

**Comment by DmitriK** [comment]
Unfortunately, Firefox prevents content scripts from running inside internal pages such as the new tab page, so the extension cannot fix this issue.

**Comment by fbruetting** [comment]
Could you file a bug report at Mozilla, to get an idea if this probably could be solved?
