### ISSUE TITLE
High cpu usage on new Google Calendar layout

### ISSUE THREAD

**Issue by MathyV** [DmitriK/darkContrast#33]
I'm having quite some issues with the new Google Calendar layout. I first thought it was because of my update to FF 57 but I now traced it back to this add-on. When it is disabled there are no issues. When it is enabled the cpu usage goes up, FF slows down and the calendar becomes almost unusable.

**Comment by DmitriK** [comment]
I can reproduce this. While I investigate, hopefully adding the domain to the blacklist helps avoid the issue until the fix is ready.

**Comment by MathyV** [comment]
It does. It looks strange with the add-on enabled anyway, but that's
another bug :D

--
Met vriendelijke groeten,
Best regards,

Mathy Vanvoorden

2017-11-30 23:18 GMT+01:00 Dmitri Kourennyi <notifications@github.com>:

**Comment by DmitriK** [comment]
This should be fixed in the 2.0.x release (And it does the right thing now instead of making it strange)

**Comment by MathyV** [comment]
It seems to work much better now, thx.

Had to manually install the update BTW, FF was not detecting the new version.

**Comment by DmitriK** [comment]
Good to hear. Closing.
