### ISSUE TITLE
Cannot install from firefox addon page

### ISSUE THREAD

**Issue by unlink2** [DmitriK/darkContrast#39]
Hi!

I've been trying to install this extension from the firefox addons page, however upon downloading Firefox notifies me that the addon seems to be corrupted.

**Comment by unlink2** [comment]
Sorry about that. A minute after opening the issue I saw the issue was realted to my /tmp directory running full. *Hides in shame corner*

**Comment by DmitriK** [comment]
No worries. Unlikely I would have come up with that as a possible issue on my own. Helps to add it to the mental war chest if something similar gets reported
