### ISSUE TITLE
Replace "Turn off" button with "Turn on" when in whitelist mode.

### ISSUE THREAD

**Issue by xnick** [DmitriK/darkContrast#40]
It would allow us to preview what the effect of putting the current page in the whitelist would be, vs forcing standard colours. It will also help to keep the whitelist from getting polluted with websites you might never visit again.

Thanks

**Comment by DmitriK** [comment]
This should be fixed in v2.0.4

**Comment by xnick** [comment]
It works great. I've been using it for a while now. (I'm building from git)

Thanks.
