### ISSUE TITLE
impossible on firefox homepage

### ISSUE THREAD

**Issue by polo51** [DmitriK/darkContrast#41]
not working on a firefox 58 internal page type : about:home / about:newtab with a dark theme the black search bar is so ugly :S on forced standard color, it's good...!

**Comment by DmitriK** [comment]
I looked at this briefly a while back, and was surprised that the force action actually worked. The extension normally does not have permissions to modify "about:*" pages. Unfortunately, it does appear to be blocked now, so I'm back to being unable to fix this.

Fortunately, the 61.0beta that I'm running finally has a dark themed "about:home" that matches the browser theme, so this should no longer be an issue.
