### ISSUE TITLE
forcing it on other extensions?

### ISSUE THREAD

**Issue by ghost** [DmitriK/darkContrast#45]
This is probably impossible and forever will be _because secuirty_ but it would be awesome if also text from other extensions had proper contrast, most don't ship with proper css and have dark text on dark (native) firefox background

**Comment by DmitriK** [comment]
As you suspect, it's not currently possible, and likely will never be. Specifically, if I try to force the extension to run on another extension's page, I get a tab permission error, and there is no way that I know of to give myself that permission.
I've noticed that FF is doing better with the coverage of it's own dark theme, so hopefully other extension authors will realize that some people have dark themes and will adjust accordingly.
