### ISSUE TITLE
Text on YouTube is dark text on dark background

### ISSUE THREAD

**Issue by MirceaMx** [DmitriK/darkContrast#48]
As the title states, text on Youtube - which is a very popular site, is dark text on dark background. 
Screenshot attached:

![screenshot_20180819_065415](https://user-images.githubusercontent.com/40819799/44305293-c61f1c80-a37c-11e8-979e-fcb6b24094e3.png)

**Comment by DmitriK** [comment]
Should be fixed in the 2.0.6 release that I just submitted. May take some time for Mozilla to approve it.

**Comment by MirceaMx** [comment]
I will expect for it to be updated. Currently on version 2.0.5. Thanks.
