### ISSUE TITLE
Firefox freezes, because of specific content

### ISSUE THREAD

**Issue by dvaerum** [DmitriK/darkContrast#49]
### Description
When I go to sites with my countries digital sign-in, Firefox freezes and I have to wait for Firefox to ask me if I want to stop the script.
![screenshot_20181031_202614](https://user-images.githubusercontent.com/6872940/47815774-982d5f80-dd51-11e8-89b6-210f6aca5763.png)

### Reproduce
Just go to one of these to sites and you will see the problem.
https://logon.e-boks.dk/nemid/logon?siteid=21
https://jutlander-netbank.dk/

### System Info
Firefox 63.0 (and older versions)
Text Contrast for Dark Themes 2.1.2 (and older versions)
Linux (Arch Linux)

**Comment by DmitriK** [comment]
I can reproduce this with a clean FF install. Something related to the frame of that login feature. Will look into it, sorry it fails so spectacularly.
You should be able to add the individual domains to the "Force standard colors:" list as a work-around until this gets fixed.

**Comment by DmitriK** [comment]
Just pushed a version that should fix this issue

**Comment by dvaerum** [comment]
You are fucking awesome, thanks you so much. I should have put some effort in to reporting this bug earlier :sweat_smile:
